'use client';
import { useState, type FormEvent } from 'react';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { ArrowLeft, ArrowRight, CheckCircle2, ShieldCheck } from 'lucide-react';
import { api, ApiError } from '@/lib/api';
import type { Comparison, ExpectationCreate, ExpectationType } from '@/lib/types';
import { comparisonLabels, humanize, number } from '@/lib/presentation';
import { manualExpectation } from '@/lib/manual-expectation';
import { useBoard } from '@/components/app-shell';
import { IconBox, QuietNote } from '@/components/ui';

export default function CreateExpectation() {
  const router = useRouter(); const board = useBoard();
  const [claim, setClaim] = useState(''); const [type, setType] = useState<ExpectationType>('numeric_comparison');
  const [metric, setMetric] = useState(''); const [comparison, setComparison] = useState<Comparison>('less_than');
  const [target, setTarget] = useState(''); const [sources, setSources] = useState(''); const [threshold, setThreshold] = useState('5');
  const [stage, setStage] = useState<'claim' | 'manual' | 'preview'>('claim'); const [preview, setPreview] = useState<ExpectationCreate | null>(null);
  const [error, setError] = useState<string | null>(null); const [requestId, setRequestId] = useState<string | null>(null); const [busy, setBusy] = useState(false);
  function interpret(event: FormEvent) {
    event.preventDefault(); setError(null);
    try { setPreview(manualExpectation({ claim, type, metric, comparison, target, sources, threshold })); setStage('preview'); }
    catch (error) { setError(error instanceof Error ? error.message : 'Check the fields and try again.'); }
  }
  async function create() {
    if (!preview || busy) return;
    setBusy(true); setError(null); setRequestId(null);
    try { const row = await api.createExpectation(preview); board.reload(); router.push(`/expectations/${row.id}`); }
    catch (error) { setError(error instanceof Error ? error.message : 'Your expectation didn’t save. Please try again.'); setRequestId(error instanceof ApiError ? error.requestId ?? null : null); setBusy(false); }
  }
  return <><Link href="/expectations" className="back-link"><ArrowLeft size={17} />Back to Expectations</Link><div className="create-wrap"><header className="create-header"><span className="eyebrow">ONE LESS THING ON YOUR MIND</span><h1>{stage === 'preview' ? 'Here’s what I’ll watch' : 'What are you counting on?'}</h1><p>{stage === 'preview' ? 'Take a moment to check the details. You’re in control.' : 'Tell us what you expect. Start with the things that matter to you.'}</p></header><div className="step-strip" aria-label="Setup progress"><span className={stage === 'claim' ? 'current' : ''}>01 · Your expectation</span><span className={stage === 'manual' ? 'current' : ''}>02 · Set the criteria</span><span className={stage === 'preview' ? 'current' : ''}>03 · Confirm</span></div>
    {stage === 'claim' && <form className="card create-card" onSubmit={event => { event.preventDefault(); if (claim.trim()) { setStage('manual'); setError(null); } }}><label htmlFor="claim">In your own words</label><textarea id="claim" autoFocus value={claim} onChange={event => setClaim(event.target.value)} placeholder="I’ve been using less AC, so my next electric bill should be lower." required rows={5} maxLength={5000} /><div className="create-hint"><ShieldCheck size={18} /><span>We’ll help you define what matching looks like.</span></div><button className="button primary" type="submit" disabled={!claim.trim()}>Count on this <ArrowRight size={17} /></button></form>}
    {stage === 'manual' && <form className="card create-card" onSubmit={interpret}><div className="manual-notice"><strong>Manual setup</strong><p>Automatic interpretation is coming later. For now, choose the criteria CountOn should check.</p></div><label htmlFor="edit-claim">Your expectation</label><textarea id="edit-claim" value={claim} onChange={event => setClaim(event.target.value)} required rows={2} /><div className="form-grid"><div><label htmlFor="type">What kind of check?</label><select id="type" value={type} onChange={event => setType(event.target.value as ExpectationType)}><option value="numeric_comparison">Compare a number</option><option value="boolean">Confirm something happened</option><option value="temporal">Time-based · evaluation not available</option><option value="event">Event-based · evaluation not available</option></select></div><div><label htmlFor="metric">Metric to watch</label><input id="metric" value={metric} onChange={event => setMetric(event.target.value)} placeholder="e.g. total_cost" maxLength={100} required /><p className="caption">The exact metric supplied by your evidence source.</p></div>{type === 'numeric_comparison' && <><div><label htmlFor="comparison">Expected behavior</label><select id="comparison" value={comparison} onChange={event => setComparison(event.target.value as Comparison)}>{Object.entries(comparisonLabels).map(([value, label]) => <option value={value} key={value}>{label}</option>)}</select></div><div><label htmlFor="target">Target value</label><input id="target" type="number" step="any" value={target} onChange={event => setTarget(event.target.value)} placeholder="Your numerical target" required /></div></>}<div className="span-two"><label htmlFor="sources">Evidence sources</label><input id="sources" value={sources} onChange={event => setSources(event.target.value)} placeholder="e.g. utility_bill, utility_usage" /><p className="caption">Comma-separated source identifiers. This does not connect a provider.</p></div><div><label htmlFor="tolerance">Materiality tolerance (%)</label><input id="tolerance" type="number" min="0" max="100" step="any" value={threshold} onChange={event => setThreshold(event.target.value)} required /></div></div>{(type === 'temporal' || type === 'event') && <p className="manual-notice">You can save this expectation, but its result will remain unknown while this evaluation type is unsupported.</p>}{error && <p className="inline-error" role="alert">{error}</p>}<div className="actions"><button className="button primary" type="submit">Review expectation <ArrowRight size={17} /></button><button className="button ghost" type="button" onClick={() => setStage('claim')}>Back</button></div></form>}
    {stage === 'preview' && preview && <section className="card create-card preview-card"><IconBox icon={CheckCircle2} /><span className="demo-badge">Manually defined · no AI interpretation</span><h2>“{preview.claim}”</h2><dl><div><dt>What I’ll watch</dt><dd>{humanize(preview.metric ?? 'Expectation')}</dd></div><div><dt>Expected behavior</dt><dd>{preview.type === 'numeric_comparison' && preview.comparison ? `${comparisonLabels[preview.comparison]} ${number(preview.target_value ?? 0)}` : preview.type === 'boolean' ? 'Confirmation (true)' : 'Time-based or event evidence; evaluation unavailable'}</dd></div><div><dt>Evidence sources</dt><dd>{preview.evidence_sources.map(humanize).join(', ') || 'Not specified'}</dd></div><div><dt>Tolerance</dt><dd>{number(preview.materiality_threshold * 100, 'percent')}</dd></div></dl>{error && <p className="inline-error" role="alert">{error}{requestId && <span className="caption">Request reference: {requestId}</span>}</p>}<div className="actions"><button className="button primary" onClick={create} disabled={busy}>{busy ? 'Saving your expectation…' : 'Start monitoring'}<ArrowRight size={17} /></button><button className="button ghost" onClick={() => { setStage('manual'); setError(null); }} disabled={busy}>Edit</button></div><p className="caption">Saving sets up the expectation. Live provider ingestion and background scheduling are not available yet.</p></section>}
    <QuietNote>A little clarity starts with knowing what you expect.</QuietNote></div></>;
}
