"""
Pydantic Models for CountOn AI Layer
"""

from typing import Optional, List, Literal, Any
from pydantic import BaseModel, Field, model_validator


# Supported expectation types
ExpectationType = Literal[
    "numeric_comparison",
    "event_occurrence",
    "event_absence",
    "delivery",
    "conversation_commitment",
]

# Supported comparison operators
ComparisonOperator = Literal[
    "less_than",
    "greater_than",
    "equal",
    "exists",
    "not_exists",
]

# Supported status values
ExpectationStatus = Literal[
    "monitoring",
    "fulfilled",
    "mismatch",
    "unknown",
    "resolved",
]


class Expectation(BaseModel):
    """
    Represents a machine-testable expectation extracted from a user's casual statement.
    """
    id: Optional[str] = Field(default=None, description="Unique identifier for the expectation")
    claim: str = Field(..., description="Original or normalized statement claim")
    type: ExpectationType = Field(..., description="Category of the expectation")
    metric: Optional[str] = Field(default=None, description="Target metric being measured (e.g., total_cost, energy_usage)")
    comparison: Optional[ComparisonOperator] = Field(default=None, description="Comparison logic")
    baseline: Optional[float] = Field(default=None, description="Reference baseline value if specified")
    deadline: Optional[str] = Field(default=None, description="Target deadline or timeframe")
    evidence_sources: List[str] = Field(default_factory=list, description="Relevant evidence sources (e.g. utility_bill, ring, bee)")
    materiality_threshold: float = Field(default=0.05, description="Tolerance threshold for numeric variance")
    status: ExpectationStatus = Field(default="monitoring", description="Lifecycle status of the expectation")


class ClarificationRequest(BaseModel):
    """
    Represents a structured request for user clarification when input is ambiguous or missing fields.
    """
    required: bool = Field(default=True, description="Whether clarification is required before proceeding")
    question: Optional[str] = Field(default=None, description="Human-friendly clarification question to ask the user")
    missing_fields: List[str] = Field(default_factory=list, description="List of missing or ambiguous fields")
    draft_expectation: Optional[dict[str, Any]] = Field(default=None, description="Partial expectation draft accumulated so far")


class CancellationRequest(BaseModel):
    """
    Represents a structured intent to cancel an expectation.
    """
    expectation_id: Optional[str] = Field(default=None, description="ID of the expectation to cancel if provided")
    target_claim: Optional[str] = Field(default=None, description="Target claim or subject to cancel")
    reason: Optional[str] = Field(default=None, description="Optional cancellation reason")


class CorrectionRequest(BaseModel):
    """
    Represents a structured user correction or amendment to an existing expectation.
    """
    expectation_id: Optional[str] = Field(default=None, description="ID of the expectation being corrected")
    field: Optional[str] = Field(default=None, description="Field being updated (e.g. deadline, baseline, metric)")
    new_value: Any = Field(default=None, description="New value for the field")


class ExpectationCompilationResult(BaseModel):
    """
    Wrapper returned by compile_expectation.
    Contains either a valid Expectation, ClarificationRequest, or CancellationRequest.
    """
    kind: Literal["expectation", "clarification", "cancellation"] = Field(..., description="Discriminator for result type")
    expectation: Optional[Expectation] = Field(default=None, description="Compiled expectation if kind=='expectation'")
    clarification: Optional[ClarificationRequest] = Field(default=None, description="Clarification request if kind=='clarification'")
    cancellation: Optional[CancellationRequest] = Field(default=None, description="Cancellation request if kind=='cancellation'")
    is_correction: bool = Field(default=False, description="True if this compilation represents a correction or update to an existing expectation")

    @model_validator(mode="after")
    def validate_payload(self) -> "ExpectationCompilationResult":
        if self.kind == "expectation" and self.expectation is None:
            raise ValueError("expectation must be provided when kind is 'expectation'")
        if self.kind == "clarification" and self.clarification is None:
            raise ValueError("clarification must be provided when kind is 'clarification'")
        if self.kind == "cancellation" and self.cancellation is None:
            raise ValueError("cancellation must be provided when kind is 'cancellation'")
        return self


class InvestigationResult(BaseModel):
    """
    Represents an evidence-based explanation generated by the Investigator after a confirmed MISMATCH.
    """
    explanation: str = Field(..., description="Clear human-friendly explanation of why the mismatch occurred")
    key_factors: List[str] = Field(default_factory=list, description="Key evidence factors that contributed to the mismatch")
    confidence: float = Field(..., ge=0.0, le=1.0, description="Confidence score between 0.0 and 1.0")


class Evidence(BaseModel):
    """
    Normalized CountOn Evidence object consumed by the Investigator.
    Independent of specific providers (Ring, Bee, Utility, etc.).
    """
    expectation_id: Optional[str] = Field(default=None, description="ID of associated expectation")
    source: str = Field(..., description="Source of evidence (e.g. utility_usage, ring, bee, billing)")
    metric: Optional[str] = Field(default=None, description="Metric identifier")
    value: Any = Field(..., description="Observed value (numeric, string, dict, boolean, etc.)")
    unit: Optional[str] = Field(default=None, description="Unit of measurement if applicable")
    timestamp: Optional[str] = Field(default=None, description="ISO timestamp or string indicator")
    confidence: float = Field(default=1.0, ge=0.0, le=1.0, description="Confidence score of the evidence data")
    description: Optional[str] = Field(default=None, description="Human readable description of the evidence")


class EvaluationResult(BaseModel):
    """
    Deterministic evaluation result supplied by evaluation engine.
    """
    result: Literal["MATCH", "UNKNOWN", "MISMATCH"] = Field(..., description="Evaluation verdict")
    expected: Optional[str] = Field(default=None, description="Description of expected outcome")
    observed_change_percent: Optional[float] = Field(default=None, description="Percentage change observed if numeric")
    materiality_threshold: Optional[float] = Field(default=0.05, description="Materiality threshold used")
    contradiction: bool = Field(default=False, description="True if a contradiction was confirmed")
    details: Optional[dict[str, Any]] = Field(default=None, description="Additional context")
